package com.fosun.fact.t360;


import com.fosun.fdrools.tools.*;
import com.fosun.fdrools.tools.dto.DynamicRuleInfoDTO;
import com.fosun.fdrools.tools.dto.RuleCommonDTO;
import com.fosun.fdrools.tools.dto.RuleParamDataDTO;
import com.fosun.fdrools.tools.dto.RuleDataSourceDTO;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.JSON;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

function Boolean doValidationT360(String ruleCode,RuleCommonDTO commonDTO,RuleParamDataDTO paramDataDTO,Map ruleDataSourceMap,RuleResultDTO resultDTO){
   Logger.info(" 执行  T360");
    if(!Tools.isRuleCodeOK(ruleCode,"T360")){
        return Boolean.FALSE;
    }
    
    if(!ruleDataSourceMap.isEmpty()){
        //2年内机构查询次数>0 
        int count = 0;//记录数
        //jxlmi数据源
        RuleDataSourceDTO afDataSource = (RuleDataSourceDTO)ruleDataSourceMap.get("JxlMI");
        JSONObject resObject = (JSONObject)afDataSource.getDsRes();
        JSONObject jsonObject = JSON.parseObject(resObject.getString("userSearchedStatistic"));
        if (jsonObject != null && jsonObject.containsKey("searched_org_cnt")) {
                String searchedOrgCnt = jsonObject.getString("searched_org_cnt");
                if (searchedOrgCnt != null) {
                    count = Integer.valueOf(searchedOrgCnt);
                    if (count > 0) {
                        return Boolean.TRUE;
                    }
                }
        }
    }
    return Boolean.FALSE;
}

rule "T360"
when

$ruleResultDTO:RuleResultDTO();
$dynamicRuleInfoDTO:DynamicRuleInfoDTO(doValidationT360(ruleCode,ruleCommonDTO,ruleParamDataDTO,ruleDataSourceMap,$ruleResultDTO));
then

Map<String,Object> extraMap = new HashMap<String,Object>();
extraMap.put("testMap",123);
$ruleResultDTO.setResult(Tools.HIT);
$ruleResultDTO.setExtraResultMap(extraMap);
$dynamicRuleInfoDTO.setRuleResultDTO($ruleResultDTO);
end