package com.fosun.fact.d342;


import com.fosun.fdrools.tools.*;
import com.fosun.fdrools.tools.dto.DynamicRuleInfoDTO;
import com.fosun.fdrools.tools.dto.RuleCommonDTO;
import com.fosun.fdrools.tools.dto.RuleParamDataDTO;
import com.fosun.fdrools.tools.dto.RuleDataSourceDTO;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.JSON;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.Date;

function Boolean doValidationD342(String ruleCode,RuleCommonDTO commonDTO,RuleParamDataDTO paramDataDTO,Map ruleDataSourceMap,RuleResultDTO resultDTO){
   Logger.info(" 执行  D342");
    if(!Tools.isRuleCodeOK(ruleCode,"D342")){
        return Boolean.FALSE;
    }
    
    if(!ruleDataSourceMap.isEmpty()){
        //命中前科
        //海鑫数据源
        RuleDataSourceDTO afDataSource = (RuleDataSourceDTO)ruleDataSourceMap.get("HaiXin001");
        JSONObject resObject = (JSONObject)afDataSource.getDsRes();
        String scoreStr = resObject.getString("score");
        Integer score = Integer.valueOf(scoreStr);
        // 如果海鑫分数在400~499：量富不良分=海鑫分数/10+30，舍弃小数点后数据。（60~69分）（前科）
        if (score >= 300 && score <= 399) {
            return Boolean.TRUE;
        }
    }
    return Boolean.FALSE;
}

rule "D342"
when

$ruleResultDTO:RuleResultDTO();
$dynamicRuleInfoDTO:DynamicRuleInfoDTO(doValidationD342(ruleCode,ruleCommonDTO,ruleParamDataDTO,ruleDataSourceMap,$ruleResultDTO));
then

Map<String,Object> extraMap = new HashMap<String,Object>();
extraMap.put("testMap",123);
$ruleResultDTO.setResult(Tools.HIT);
$ruleResultDTO.setExtraResultMap(extraMap);
$dynamicRuleInfoDTO.setRuleResultDTO($ruleResultDTO);
end