package com.fosun.fact;

import com.fosun.fdrools.tools.*;

function Boolean doValidationD300(String ruleId,RuleParamHolderDTO ruleParamHolderDTO, RuleResultDTO ruleResultDTO){
    
    
    if(!Tools.isRuleCodeOK(ruleId,"D300")){
        return Boolean.FALSE;
    }
    JSONObject obj = ruleParamHolderDTO.getSoloParam();
    if(obj != null && obj.get("province") != null){
        String province = obj.getString("province");
        if(province.contains("福建") || province.contains("山东") || province.contains("内蒙古") || province.contains("河北")){
            return Boolean.TRUE;
        }
       
    }
    return Boolean.FALSE;
}

rule "D300"
salience -1
no-loop true
when
$ruleResultDTO:RuleResultDTO();
$ruleInfoDTO:RuleInfoDTO(doValidationD300(ruleCode,ruleParamHolderDTO,$ruleResultDTO));

then
$ruleResultDTO.setResult(Tools.HIT);
$ruleInfoDTO.setRuleResultDTO($ruleResultDTO);
end;