package com.fosun.fact;

import com.fosun.fdrools.tools.*;

function Boolean doValidationD303(String ruleId,RuleParamHolderDTO ruleParamHolderDTO, RuleResultDTO ruleResultDTO){
    
   
    if(!Tools.isRuleCodeOK(ruleId,"D303")){
        return false;
    }
    JSONObject obj = ruleParamHolderDTO.getSoloParam();
        if(obj.get("inTime")!=null){
             String inTime = obj.getString("inTime");
             if("03".equals(inTime) || "04".equals(inTime) || "1".equals(inTime) || "99".equals(inTime)){
                 return Boolean.TRUE;
             }
        }
    
    return Boolean.FALSE;
}

rule "D303"
salience -1
no-loop true
when
$ruleResultDTO:RuleResultDTO();
$ruleInfoDTO:RuleInfoDTO(doValidationD303(ruleCode,ruleParamHolderDTO,$ruleResultDTO));

then
$ruleResultDTO.setResult(Tools.HIT);
$ruleInfoDTO.setRuleResultDTO($ruleResultDTO);
end;