package com.fosun.fact;

import com.fosun.fdrools.tools.*;

function Boolean doValidationD306(String ruleId,RuleParamHolderDTO ruleParamHolderDTO, RuleResultDTO ruleResultDTO){
    
    
    if(!Tools.isRuleCodeOK(ruleId,"D306")){
        return false;
    }
    List<JSONObject> jsonList = ruleParamHolderDTO.getArrayParams();
    for(JSONObject obj : jsonList){
        if(obj.get("matchRatio")!=null){
             Double matchRatio = obj.getDouble("matchRatio");
             Logger.info("D306 " + "" + matchRatio);
             if(matchRatio >= 0.8){
                 return Boolean.TRUE;
             }
        }
    }
    return Boolean.FALSE;
}

rule "D306"

when
$ruleResultDTO:RuleResultDTO();
$ruleInfoDTO:RuleInfoDTO(doValidationD306(ruleCode,ruleParamHolderDTO,$ruleResultDTO));

then
$ruleResultDTO.setResult(Tools.HIT);
$ruleInfoDTO.setRuleResultDTO($ruleResultDTO);
end;