package com.fosun.fact;

import com.fosun.fdrools.tools.*;

function Boolean doValidationD316(String ruleId,RuleParamHolderDTO ruleParamHolderDTO, RuleResultDTO ruleResultDTO){
    
    
    if(!Tools.isRuleCodeOK(ruleId,"D316")){
        return Boolean.FALSE;
    }
    JSONObject obj = ruleParamHolderDTO.getSoloParam();
    if(obj != null && obj.get("overdueTimes180") != null){
        Integer overdueTimes180 = obj.getInteger("overdueTimes180");
        if(overdueTimes180 >= 1){
            return Boolean.TRUE;
        }
    }
    return Boolean.FALSE;
}

rule "D316"
salience -1
no-loop true
when
$ruleResultDTO:RuleResultDTO();
$ruleInfoDTO:RuleInfoDTO(doValidationD316(ruleCode,ruleParamHolderDTO,$ruleResultDTO));

then
$ruleResultDTO.setResult(Tools.HIT);
$ruleInfoDTO.setRuleResultDTO($ruleResultDTO);
end;