package com.fosun.fact;

import com.fosun.fdrools.tools.*;

function Boolean doValidationD319(String ruleId,RuleParamHolderDTO ruleParamHolderDTO, RuleResultDTO ruleResultDTO){
    
    
    if(!Tools.isRuleCodeOK(ruleId,"D319")){
        return Boolean.FALSE;
    }
    JSONObject obj = ruleParamHolderDTO.getSoloParam();
    
    if(obj != null && obj.get("score") != null){
        Double score = obj.getDouble("score");
        if(score >= 0.7){
           return Boolean.TRUE;
        }
    }
    return Boolean.FALSE;
}

rule "D319"
salience -1
no-loop true
when
$ruleResultDTO:RuleResultDTO();
$ruleInfoDTO:RuleInfoDTO(doValidationD319(ruleCode,ruleParamHolderDTO,$ruleResultDTO));

then
$ruleResultDTO.setResult(Tools.HIT);
$ruleInfoDTO.setRuleResultDTO($ruleResultDTO);
end;