package com.fosun.fact;

import com.fosun.fdrools.tools.*;

function Boolean doValidationD320(String ruleId,RuleParamHolderDTO ruleParamHolderDTO, RuleResultDTO ruleResultDTO){
    
    
    if(!Tools.isRuleCodeOK(ruleId,"D320")){
        return Boolean.FALSE;
    }
    JSONObject obj = ruleParamHolderDTO.getSoloParam();
    
    if(obj != null && obj.get("phoneGrayScore") != null){
        Double phoneGrayScore = obj.getDouble("phoneGrayScore");
        if(phoneGrayScore <= 20.0){
           return Boolean.TRUE;
        }
    }
    return Boolean.FALSE;
}

rule "D320"
salience -1
no-loop true
when
$ruleResultDTO:RuleResultDTO();
$ruleInfoDTO:RuleInfoDTO(doValidationD320(ruleCode,ruleParamHolderDTO,$ruleResultDTO));

then
$ruleResultDTO.setResult(Tools.HIT);
$ruleInfoDTO.setRuleResultDTO($ruleResultDTO);
end;