package com.fosun.fact;

import com.fosun.fdrools.tools.*;

function Boolean doValidationD321(String ruleId,RuleParamHolderDTO ruleParamHolderDTO, RuleResultDTO ruleResultDTO){
    
    
    if(!Tools.isRuleCodeOK(ruleId,"D321")){
        return Boolean.FALSE;
    }
    JSONObject obj = ruleParamHolderDTO.getSoloParam();
    if(obj != null && obj.getInteger("age") != null){
        Integer age = obj.getInteger("age");
        if(age >= 55 || age <= 23){
            return Boolean.TRUE;
        }
       
    }
    return Boolean.FALSE;
}

rule "D321"
salience -1
no-loop true
when
$ruleResultDTO:RuleResultDTO();
$ruleInfoDTO:RuleInfoDTO(doValidationD321(ruleCode,ruleParamHolderDTO,$ruleResultDTO));

then
$ruleResultDTO.setResult(Tools.HIT);
$ruleInfoDTO.setRuleResultDTO($ruleResultDTO);
end;