package com.fosun.fact;

import com.fosun.fdrools.tools.*;

function Boolean doValidationD342(String ruleId,RuleParamHolderDTO ruleParamHolderDTO, RuleResultDTO ruleResultDTO){
    
    
    if(!Tools.isRuleCodeOK(ruleId,"D342")){
        return false;
    }
    JSONObject obj = ruleParamHolderDTO.getSoloParam();
    //Logger.info("RuleId = " + ruleId + "  ** "+ ruleParamHolderDTO.getSoloParam().getInteger("score"));
        // 如果海鑫分数在400~499：量富不良分=海鑫分数/10+30，舍弃小数点后数据。（60~69分）（前科）
        if(obj.get("score")!=null){
             Integer score = obj.getInteger("score");
             if(score >= 300 && score <= 399){
                 return Boolean.TRUE;
             }
        }
    
    return Boolean.FALSE;
}

rule "D342"
salience -1
no-loop true
lock-on-active true
when
$ruleResultDTO:RuleResultDTO();
$ruleInfoDTO:RuleInfoDTO(doValidationD342(ruleCode,ruleParamHolderDTO,$ruleResultDTO));

then
$ruleResultDTO.setResult(Tools.HIT);
$ruleInfoDTO.setRuleResultDTO($ruleResultDTO);
end;