package com.fosun.fact;

import com.fosun.fdrools.tools.*;

function Boolean doValidationD399(String ruleId,RuleParamHolderDTO ruleParamHolderDTO, RuleResultDTO ruleResultDTO){
    
    
    if(!Tools.isRuleCodeOK(ruleId,"D399")){
        return false;
    }
    JSONObject obj = ruleParamHolderDTO.getSoloParam();
        //在网状态≠正常在用（天翼） 1:正常再用、 2:销户、 3:停机、  4:未启用
        if(obj.get("netWorkStastus")!=null){
             String netWorkStastus = obj.getString("netWorkStastus");
             if("2".equals(netWorkStastus) || "3".equals(netWorkStastus) || "4".equals(netWorkStastus)){
                 return Boolean.TRUE;
             }
        }
    
    return Boolean.FALSE;
}

rule "D399"
salience -1
no-loop true
lock-on-active true
when
$ruleResultDTO:RuleResultDTO();
$ruleInfoDTO:RuleInfoDTO(doValidationD399(ruleCode,ruleParamHolderDTO,$ruleResultDTO));

then
$ruleResultDTO.setResult(Tools.HIT);
$ruleInfoDTO.setRuleResultDTO($ruleResultDTO);
end;