package com.fosun.fact;

import com.fosun.fdrools.tools.*;

function Boolean doValidationD400(String ruleId,RuleParamHolderDTO ruleParamHolderDTO, RuleResultDTO ruleResultDTO){
    
    
    if(!Tools.isRuleCodeOK(ruleId,"D400")){
        return false;
    }
    JSONObject obj = ruleParamHolderDTO.getSoloParam();
        //手机号与申请人姓名=否(天翼) 1：验证一致、2：验证不一致
        if(obj.get("twoElementsCheckResult")!=null){
             String twoElementsCheckResult = obj.getString("twoElementsCheckResult");
             if("2".equals(twoElementsCheckResult)){
                 return Boolean.TRUE;
             }
        }
    
    return Boolean.FALSE;
}

rule "D400"
salience -1
no-loop true
lock-on-active true
when
$ruleResultDTO:RuleResultDTO();
$ruleInfoDTO:RuleInfoDTO(doValidationD400(ruleCode,ruleParamHolderDTO,$ruleResultDTO));

then
$ruleResultDTO.setResult(Tools.HIT);
$ruleInfoDTO.setRuleResultDTO($ruleResultDTO);
end;