package com.fosun.fact;

import com.fosun.fdrools.tools.*;

function Boolean doValidationD403(String ruleId,RuleParamHolderDTO ruleParamHolderDTO, RuleResultDTO ruleResultDTO){
    
    
    if(!Tools.isRuleCodeOK(ruleId,"D403")){
        return false;
    }
    JSONObject obj = ruleParamHolderDTO.getSoloParam();
        //手机入网时间≤6个月（天翼） 03: (0,3]、06: (3,6]、12:(6,12]、24: (12,24]、99: (24,+)
        if(obj.get("netWorkTime")!=null){
             String netWorkTime = obj.getString("netWorkTime");
             if("03".equals(netWorkTime) || "06".equals(netWorkTime)){
                 return Boolean.TRUE;
             }
        }
    
    return Boolean.FALSE;
}

rule "D403"
salience -1
no-loop true
lock-on-active true
when
$ruleResultDTO:RuleResultDTO();
$ruleInfoDTO:RuleInfoDTO(doValidationD403(ruleCode,ruleParamHolderDTO,$ruleResultDTO));

then
$ruleResultDTO.setResult(Tools.HIT);
$ruleInfoDTO.setRuleResultDTO($ruleResultDTO);
end;