package com.fosun.fact;

import com.fosun.fdrools.tools.*;

function Boolean doValidationR300(String ruleId,RuleParamHolderDTO ruleParamHolderDTO, RuleResultDTO ruleResultDTO){
    
    
    if(!Tools.isRuleCodeOK(ruleId,"R300")){
        return Boolean.FALSE;
    }
    JSONObject obj = ruleParamHolderDTO.getSoloParam();
    List<JSONObject> jsonList = ruleParamHolderDTO.getArrayParams();
    if(obj != null && obj.get("status") != null){
        String status = obj.getString("status");
        if(!status.equals("0")){
            for(JSONObject arrayObj:jsonList){
                if(arrayObj.getInteger("repayState")!=null){
                    Integer repayState = arrayObj.getInteger("repayState");
                    if(repayState == 3 ){
                      return Boolean.TRUE;
                    }
                }
            }
        }else{
            return Boolean.FALSE;
        }
    }
    return Boolean.FALSE;
}

rule "R300"
salience -1
no-loop true
when
$ruleResultDTO:RuleResultDTO();
$ruleInfoDTO:RuleInfoDTO(doValidationR300(ruleCode,ruleParamHolderDTO,$ruleResultDTO));

then
$ruleResultDTO.setResult(Tools.HIT);
$ruleInfoDTO.setRuleResultDTO($ruleResultDTO);
end;