package com.fosun.fact;

import com.fosun.fdrools.tools.*;

function Boolean doValidationT300(String ruleId,RuleParamHolderDTO ruleParamHolderDTO, RuleResultDTO ruleResultDTO){
    
    
    if(!Tools.isRuleCodeOK(ruleId,"T300")){
        return Boolean.FALSE;
    }
    JSONObject obj = ruleParamHolderDTO.getSoloParam();
    
    if(obj != null && obj.get("nameMatchMobile") != null){
        String nameMatchMobile = obj.getString("nameMatchMobile");
        if(nameMatchMobile.equals("1")){
           return Boolean.TRUE;
        }
    }
    return Boolean.FALSE;
}

rule "T300"
salience -1
no-loop true
when
$ruleResultDTO:RuleResultDTO();
$ruleInfoDTO:RuleInfoDTO(doValidationT300(ruleCode,ruleParamHolderDTO,$ruleResultDTO));

then
$ruleResultDTO.setResult(Tools.HIT);
$ruleInfoDTO.setRuleResultDTO($ruleResultDTO);
end;