package com.fosun.fact;

import com.fosun.fdrools.tools.*;

function Boolean doValidationT308(String ruleId,RuleParamHolderDTO ruleParamHolderDTO, RuleResultDTO ruleResultDTO){
    
    
    if(!Tools.isRuleCodeOK(ruleId,"T308")){
        return Boolean.FALSE;
    }
    
    List<JSONObject> jsonList = ruleParamHolderDTO.getArrayParams();
        for(JSONObject arrayObj:jsonList){
                if(arrayObj.getDouble("matchRatio")!=null && arrayObj.getInteger("personFlag")!=null){
                    Double matchRatio = arrayObj.getDouble("matchRatio");
                    Integer personFlag = arrayObj.getInteger("personFlag");
                    if(matchRatio  >= 0.5 && personFlag == 1 ){
                        return Boolean.TRUE;
                    }
                }
            }
    return Boolean.FALSE;
}

rule "T308"
salience -1
no-loop true
when
$ruleResultDTO:RuleResultDTO();
$ruleInfoDTO:RuleInfoDTO(doValidationT308(ruleCode,ruleParamHolderDTO,$ruleResultDTO));

then
$ruleResultDTO.setResult(Tools.HIT);
$ruleInfoDTO.setRuleResultDTO($ruleResultDTO);
end;