package com.fosun.fact;

import com.fosun.fdrools.tools.*;

function Boolean doValidationT312(String ruleId,RuleParamHolderDTO ruleParamHolderDTO, RuleResultDTO ruleResultDTO){
    
    
    if(!Tools.isRuleCodeOK(ruleId,"T312")){
        return Boolean.FALSE;
    }
    
    List<JSONObject> jsonList = ruleParamHolderDTO.getArrayParams();
        for(JSONObject arrayObj:jsonList){
                if(arrayObj.getDouble("matchRatio")!=null){
                    Double matchRatio = arrayObj.getDouble("matchRatio");
                    if(matchRatio  >= 0.5 ){
                        return Boolean.TRUE;
                    }
                }
            }
    return Boolean.FALSE;
}

rule "T312"
salience -1
no-loop true
when
$ruleResultDTO:RuleResultDTO();
$ruleInfoDTO:RuleInfoDTO(doValidationT312(ruleCode,ruleParamHolderDTO,$ruleResultDTO));

then
$ruleResultDTO.setResult(Tools.HIT);
$ruleInfoDTO.setRuleResultDTO($ruleResultDTO);
end;