package com.fosun.fact;

import com.fosun.fdrools.tools.*;

function Boolean doValidationT335(String ruleId,RuleParamHolderDTO ruleParamHolderDTO, RuleResultDTO ruleResultDTO){
    
    
    if(!Tools.isRuleCodeOK(ruleId,"T335")){
        return Boolean.FALSE;
    }
    
    List<JSONObject> jsonList = ruleParamHolderDTO.getArrayParams();
        for(JSONObject arrayObj:jsonList){
                if(arrayObj.getString("label")!=null &&  arrayObj.getInteger("count") != null){
                    String label = arrayObj.getString("label");
                    Integer count = arrayObj.getInteger("count");
                    if(label.equals("贷款") && count >= 2){
                        return Boolean.TRUE;
                    }
                }
            }
    return Boolean.FALSE;
}

rule "T335"
salience -1
no-loop true
when
$ruleResultDTO:RuleResultDTO();
$ruleInfoDTO:RuleInfoDTO(doValidationT335(ruleCode,ruleParamHolderDTO,$ruleResultDTO));

then
$ruleResultDTO.setResult(Tools.HIT);
$ruleInfoDTO.setRuleResultDTO($ruleResultDTO);
end;