package com.fosun.fact;

import com.fosun.fdrools.tools.*;

function Boolean doValidationT358(String ruleId,RuleParamHolderDTO ruleParamHolderDTO, RuleResultDTO ruleResultDTO){
    
    
    if(!Tools.isRuleCodeOK(ruleId,"T358")){
        return Boolean.FALSE;
    }
    
    List<JSONObject> jsonList = ruleParamHolderDTO.getArrayParams();
    Integer count = 0;
        for(JSONObject arrayObj:jsonList){
                if(arrayObj.getInteger("idCardFlag")!=null &&  arrayObj.getInteger("yearGap") != null){
                    Integer idCardFlag =arrayObj.getInteger("idCardFlag");
                    Integer yearGap = arrayObj.getInteger("yearGap");
                    if(idCardFlag == 1 && yearGap <=2 ){
                        count = count +1;
                    }
                    if(count > 1){
                        return Boolean.TRUE;
                    }
                }
            }
    return Boolean.FALSE;
}

rule "T358"
salience -1
no-loop true
when
$ruleResultDTO:RuleResultDTO();
$ruleInfoDTO:RuleInfoDTO(doValidationT358(ruleCode,ruleParamHolderDTO,$ruleResultDTO));

then
$ruleResultDTO.setResult(Tools.HIT);
$ruleInfoDTO.setRuleResultDTO($ruleResultDTO);
end;