package com.fosun.fact.d320;


import com.fosun.fdrools.tools.*;
import com.fosun.fdrools.tools.dto.DynamicRuleInfoDTO;
import com.fosun.fdrools.tools.dto.RuleCommonDTO;
import com.fosun.fdrools.tools.dto.RuleParamDataDTO;
import com.fosun.fdrools.tools.dto.RuleDataSourceDTO;

import com.alibaba.fastjson.JSONObject;
import java.util.List;
import java.util.Map;
import java.util.HashMap
import com.alibaba.fastjson.JSON

function Boolean doValidationD320(String ruleCode,RuleCommonDTO commonDTO,RuleParamDataDTO paramDataDTO,Map ruleDataSourceMap,RuleResultDTO resultDTO){
   Logger.info(" 执行  D320");
    if(!Tools.isRuleCodeOK(ruleCode,"D320")){
        return Boolean.FALSE;
    }
    
    if(!ruleDataSourceMap.isEmpty()){
       RuleDataSourceDTO afDataSource = (RuleDataSourceDTO)ruleDataSourceMap.get("JxlMI");
       JSONObject resObj = (JSONObject)afDataSource.getDsRes();
       String userGray = resObj.getString("userGray");
       if (userGray!=null&&userGray!=""){
            JSONObject userGrayObj = JSON.parseObject(userGray);
                   if(userGrayObj !=null&&userGrayObj.containsKey("phone_gray_score")){
                    double contactsClass1Cnt = userGrayObj.getDoubleValue("phone_gray_score");
                    if(contactsClass1Cnt<=20){
                           return Boolean.TRUE;
                    }
                   }
       }
    }
    
    return Boolean.FALSE;
}

rule "D320"
when

$ruleResultDTO:RuleResultDTO();
$dynamicRuleInfoDTO:DynamicRuleInfoDTO(doValidationD320(ruleCode,ruleCommonDTO,ruleParamDataDTO,ruleDataSourceMap,$ruleResultDTO));
then

Map<String,Object> extraMap = new HashMap<String,Object>();
extraMap.put("testMap",123);
$ruleResultDTO.setResult(Tools.HIT);
$ruleResultDTO.setExtraResultMap(extraMap);
$dynamicRuleInfoDTO.setRuleResultDTO($ruleResultDTO);
end
