package com.fosun.fact.t301;


import com.fosun.fdrools.tools.*;
import com.fosun.fdrools.tools.dto.DynamicRuleInfoDTO;
import com.fosun.fdrools.tools.dto.RuleCommonDTO;
import com.fosun.fdrools.tools.dto.RuleParamDataDTO;
import com.fosun.fdrools.tools.dto.RuleDataSourceDTO;

import com.alibaba.fastjson.JSONObject;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONArray;

function Boolean doValidationT301(String ruleCode,RuleCommonDTO commonDTO,RuleParamDataDTO paramDataDTO,Map ruleDataSourceMap,RuleResultDTO resultDTO){
   Logger.info(" 执行  T301");
    if(!Tools.isRuleCodeOK(ruleCode,"T301")){
        return Boolean.FALSE;
    }

    if(!ruleDataSourceMap.isEmpty()){
       RuleDataSourceDTO fhSxDataSource = (RuleDataSourceDTO)ruleDataSourceMap.get("FHShixin");
       JSONArray array = (JSONArray)fhSxDataSource.getDsRes();
       if(array != null && array.size()>0){
           for(int i =0;i<array.size();i++){
               JSONObject object = (JSONObject) array.get(i);
               if("shixin".equals(object.getString("dataType"))){
                    boolean flag = Tools.result(object.getString("matchratio"),object.getString("sortTimeString"),2);
                    if(flag&&!"全部已履行".equals(object.getString("lxqk"))){
                        return Boolean.TRUE;
                    }
               }
           }
       }
    }

    return Boolean.FALSE;
}

rule "T301"
when

$ruleResultDTO:RuleResultDTO();
$dynamicRuleInfoDTO:DynamicRuleInfoDTO(doValidationT301(ruleCode,ruleCommonDTO,ruleParamDataDTO,ruleDataSourceMap,$ruleResultDTO));
then

Map<String,Object> extraMap = new HashMap<String,Object>();
extraMap.put("testMap",123);
$ruleResultDTO.setResult(Tools.HIT);
$ruleResultDTO.setExtraResultMap(extraMap);
$dynamicRuleInfoDTO.setRuleResultDTO($ruleResultDTO);
end



