package com.fosun.fact.d317;


import com.fosun.fdrools.tools.*;
import com.fosun.fdrools.tools.dto.DynamicRuleInfoDTO;
import com.fosun.fdrools.tools.dto.RuleCommonDTO;
import com.fosun.fdrools.tools.dto.RuleParamDataDTO;
import com.fosun.fdrools.tools.dto.RuleDataSourceDTO;

import com.alibaba.fastjson.JSONObject;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.Date;
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;

function Boolean doValidationD317(String ruleCode,RuleCommonDTO commonDTO,RuleParamDataDTO paramDataDTO,Map ruleDataSourceMap,RuleResultDTO resultDTO){
   Logger.info(" 执行  D317");
    if(!Tools.isRuleCodeOK(ruleCode,"D317")){
        return Boolean.FALSE;
    }
    
    if(!ruleDataSourceMap.isEmpty()){
       RuleDataSourceDTO jyDataSource = (RuleDataSourceDTO)ruleDataSourceMap.get("1003");
       JSONArray array = (JSONArray) jyDataSource.getDsRes();
       JSONObject object = (JSONObject)array.get(0);
       Logger.info("参数"+array);
       String status = object.getString("loanInformation");
       Date date = Tools.addMonth(new Date(),-3);
       if(!"0".equals(status)){
           int i = 0;
           for(int j=0;j<=array.size()-1;j++){
               JSONObject param = (JSONObject)array.get(j);
               Long contractTime = Long.valueOf(param.getString("contractdate"));
               Long nowTime = date.getTime();
               if(nowTime-contractTime<=0){
                   i++;
                   Logger.info("申请日期≤近3个月，且申请笔数≥5笔数："+i);
                   if(i>=5){
                       return Boolean.TRUE;
                   }
               }
           }
       }
    }
    
    return Boolean.FALSE;
}

rule "D317"
when

$ruleResultDTO:RuleResultDTO();
$dynamicRuleInfoDTO:DynamicRuleInfoDTO(doValidationD317(ruleCode,ruleCommonDTO,ruleParamDataDTO,ruleDataSourceMap,$ruleResultDTO));
then

Map<String,Object> extraMap = new HashMap<String,Object>();
extraMap.put("testMap",123);
$ruleResultDTO.setResult(Tools.HIT);
$ruleResultDTO.setExtraResultMap(extraMap);
$dynamicRuleInfoDTO.setRuleResultDTO($ruleResultDTO);
end

