package com.fosun.fact.t335;


import com.fosun.fdrools.tools.*;
import com.fosun.fdrools.tools.dto.DynamicRuleInfoDTO;
import com.fosun.fdrools.tools.dto.RuleCommonDTO;
import com.fosun.fdrools.tools.dto.RuleParamDataDTO;
import com.fosun.fdrools.tools.dto.RuleDataSourceDTO;

import com.alibaba.fastjson.JSONObject;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSON;

function Boolean doValidationT335(String ruleCode,RuleCommonDTO commonDTO,RuleParamDataDTO paramDataDTO,Map ruleDataSourceMap,RuleResultDTO resultDTO){
   Logger.info(" 执行  T335");
    if(!Tools.isRuleCodeOK(ruleCode,"T335")){
        return Boolean.FALSE;
    }
    
    if(!ruleDataSourceMap.isEmpty()){
       RuleDataSourceDTO afDataSource = (RuleDataSourceDTO)ruleDataSourceMap.get("JxlMI");
       JSONObject resObj = (JSONObject)afDataSource.getDsRes();
       JSONObject userRegisterOrg = JSON.parseObject(resObj.getString("userRegisterOrgs"));
       if(userRegisterOrg!=null && userRegisterOrg.containsKey("register_orgs_statistics")){
           JSONArray array = (JSONArray)userRegisterOrg.get("register_orgs_statistics");
           Logger.info("解析参数"+array);
           if(array != null && array.size()>0){
	        for (int i = 0; i < array.size(); i++) {
                        JSONObject tempJson = (JSONObject)array.get(i);
                        String label = tempJson.getString("label");
                        if ("贷款".equals(label)) {
                            int count = tempJson.getInteger("count");
                            if (count >= 2) {
                                return Boolean.TRUE;
                   }
                }
            }
	    } 
       }
    }
    
    return Boolean.FALSE;
}

rule "T335"
when

$ruleResultDTO:RuleResultDTO();
$dynamicRuleInfoDTO:DynamicRuleInfoDTO(doValidationT335(ruleCode,ruleCommonDTO,ruleParamDataDTO,ruleDataSourceMap,$ruleResultDTO));
then

Map<String,Object> extraMap = new HashMap<String,Object>();
extraMap.put("testMap",123);
$ruleResultDTO.setResult(Tools.HIT);
$ruleResultDTO.setExtraResultMap(extraMap);
$dynamicRuleInfoDTO.setRuleResultDTO($ruleResultDTO);
end


