package com.fosun.fact.t379;


import com.fosun.fdrools.tools.*;
import com.fosun.fdrools.tools.dto.DynamicRuleInfoDTO;
import com.fosun.fdrools.tools.dto.RuleCommonDTO;
import com.fosun.fdrools.tools.dto.RuleParamDataDTO;
import com.fosun.fdrools.tools.dto.RuleDataSourceDTO;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

function Boolean doValidationT379(String ruleCode,RuleCommonDTO commonDTO,RuleParamDataDTO paramDataDTO,Map ruleDataSourceMap,RuleResultDTO resultDTO){
   Logger.info(" 执行  T379");
    if(!Tools.isRuleCodeOK(ruleCode,"T379")){
        return Boolean.FALSE;
    }
   
        
    if(!ruleDataSourceMap.isEmpty()){
       RuleDataSourceDTO geoDataSource = (RuleDataSourceDTO)ruleDataSourceMap.get("GEO_B11");
       if(geoDataSource!=null){
        JSONArray jsonArray = (JSONArray)geoDataSource.getDsRes();
        JSONObject jsonObject = jsonArray.getJSONObject(0);
        String contactsFrequestMatchFlag = jsonObject.getString("contactsFrequestMatchFlag");
        if ("1".equals(contactsFrequestMatchFlag)) {
           return Boolean.TRUE;
       }
       }
    }
    return Boolean.FALSE;
}

rule "T379"
when

$ruleResultDTO:RuleResultDTO();
$dynamicRuleInfoDTO:DynamicRuleInfoDTO(doValidationT379(ruleCode,ruleCommonDTO,ruleParamDataDTO,ruleDataSourceMap,$ruleResultDTO));
then

Map<String,Object> extraMap = new HashMap<String,Object>();
$ruleResultDTO.setResult(Tools.HIT);
$ruleResultDTO.setExtraResultMap(extraMap);
$dynamicRuleInfoDTO.setRuleResultDTO($ruleResultDTO);
end