package com.fosun.fact.r326;


import com.fosun.fdrools.tools.*;
import com.fosun.fdrools.tools.dto.DynamicRuleInfoDTO;
import com.fosun.fdrools.tools.dto.RuleCommonDTO;
import com.fosun.fdrools.tools.dto.RuleParamDataDTO;
import com.fosun.fdrools.tools.dto.RuleDataSourceDTO;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

function Boolean doValidationR326(String ruleCode,RuleCommonDTO commonDTO,RuleParamDataDTO paramDataDTO,Map ruleDataSourceMap,RuleResultDTO resultDTO){
   Logger.info(" 执行  R326");
    if(!Tools.isRuleCodeOK(ruleCode,"R326")){
        return Boolean.FALSE;
    }
    
    if(!ruleDataSourceMap.isEmpty()){
        //在外借款金额较大>=6万 
        //91数据源
        RuleDataSourceDTO afDataSource = (RuleDataSourceDTO)ruleDataSourceMap.get("1003");
        JSONArray resArray = (JSONArray)afDataSource.getDsRes();
        if(resArray != null){
            double amount = 0d;
            for(int i = 0; i < resArray.size(); i++ ){
                JSONObject tempJson = resArray.getJSONObject(i);
                String borrowamountStr = tempJson.getString("borrowamount");
                if (Integer.valueOf(borrowamountStr) <= 1) {
					String borroWamountCalc = Tools.borroWamountCalc(borrowamountStr);
					double borrow = Double.valueOf(borroWamountCalc);
					amount = borrow + amount;
				} else {
					Integer boor = Integer.valueOf(borrowamountStr);
					amount = (2 * boor - 1) + amount;
				}
            }
            if (amount >= 6) {
				return Boolean.TRUE;
			}
       }
       
    }
    
    return Boolean.FALSE;
}

rule "R326"
when

$ruleResultDTO:RuleResultDTO();
$dynamicRuleInfoDTO:DynamicRuleInfoDTO(doValidationR326(ruleCode,ruleCommonDTO,ruleParamDataDTO,ruleDataSourceMap,$ruleResultDTO));
then

Map<String,Object> extraMap = new HashMap<String,Object>();
extraMap.put("testMap",123);
$ruleResultDTO.setResult(Tools.HIT);
$ruleResultDTO.setExtraResultMap(extraMap);
$dynamicRuleInfoDTO.setRuleResultDTO($ruleResultDTO);
end