package com.fosun.fact.r327;


import com.fosun.fdrools.tools.*;
import com.fosun.fdrools.tools.dto.DynamicRuleInfoDTO;
import com.fosun.fdrools.tools.dto.RuleCommonDTO;
import com.fosun.fdrools.tools.dto.RuleParamDataDTO;
import com.fosun.fdrools.tools.dto.RuleDataSourceDTO;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

function Boolean doValidationR327(String ruleCode,RuleCommonDTO commonDTO,RuleParamDataDTO paramDataDTO,Map ruleDataSourceMap,RuleResultDTO resultDTO){
   Logger.info(" 执行  R327");
    if(!Tools.isRuleCodeOK(ruleCode,"R327")){
        return Boolean.FALSE;
    }
    
    if(!ruleDataSourceMap.isEmpty()){
       RuleDataSourceDTO geoDataSource = (RuleDataSourceDTO)ruleDataSourceMap.get("GEO_A3");
       if(geoDataSource!=null){
        JSONArray jsonArray = (JSONArray)geoDataSource.getDsRes();
        JSONObject jsonObject = jsonArray.getJSONObject(0);
        String inTime = jsonObject.getString("inTime");
        if ("03".equals(inTime) || "04".equals(inTime)) {
           return Boolean.TRUE;
       }
       }
       
       RuleDataSourceDTO pyDataSource = (RuleDataSourceDTO)ruleDataSourceMap.get("PY_96027");
       if(pyDataSource!=null){
        JSONArray jsonArray = (JSONArray)pyDataSource.getDsRes();
        JSONObject jsonObject = jsonArray.getJSONObject(0);
        String timeLength = jsonObject.getString("timeLength");
        if (!timeLength.contains("12个月")) {
           return Boolean.TRUE;
       }
       }
       
    }
    
    return Boolean.FALSE;
}

rule "R327"
when

$ruleResultDTO:RuleResultDTO();
$dynamicRuleInfoDTO:DynamicRuleInfoDTO(doValidationR327(ruleCode,ruleCommonDTO,ruleParamDataDTO,ruleDataSourceMap,$ruleResultDTO));
then

Map<String,Object> extraMap = new HashMap<String,Object>();
$ruleResultDTO.setResult(Tools.HIT);
$ruleResultDTO.setExtraResultMap(extraMap);
$dynamicRuleInfoDTO.setRuleResultDTO($ruleResultDTO);
end