package com.fosun.fact.d308;


import com.fosun.fdrools.tools.*;
import com.fosun.fdrools.tools.dto.DynamicRuleInfoDTO;
import com.fosun.fdrools.tools.dto.RuleCommonDTO;
import com.fosun.fdrools.tools.dto.RuleParamDataDTO;
import com.fosun.fdrools.tools.dto.RuleDataSourceDTO;

import com.alibaba.fastjson.JSONObject;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONArray;

function Boolean doValidationD308(String ruleCode,RuleCommonDTO commonDTO,RuleParamDataDTO paramDataDTO,Map ruleDataSourceMap,RuleResultDTO resultDTO){
   Logger.info(" 执行  D308");
    if(!Tools.isRuleCodeOK(ruleCode,"D308")){
        return Boolean.FALSE;
    }

    if(!ruleDataSourceMap.isEmpty()){
       RuleDataSourceDTO fhSxDataSource = (RuleDataSourceDTO)ruleDataSourceMap.get("FHZxgg");
       JSONArray array = (JSONArray)fhSxDataSource.getDsRes();
       if(array != null && array.size()>0){
           for(int i =0;i<array.size();i++){
               JSONObject object = (JSONObject) array.get(i);
               if("zxgg".equals(object.getString("dataType"))){
                    boolean flag = Tools.result(object.getString("matchratio"),object.getString("sortTimeString"),4);
                    if(flag){
                        return Boolean.TRUE;
                    }
               }
           }
       }
    }

    return Boolean.FALSE;
}
function Object doFhAddInfo(DynamicRuleInfoDTO dynamicRuleInfoDto){
    Map ruleDataSourceMap = dynamicRuleInfoDto.getRuleDataSourceMap();
    RuleDataSourceDTO fhSxDataSource = (RuleDataSourceDTO)ruleDataSourceMap.get("FHZxgg");
    JSONArray array = (JSONArray)fhSxDataSource.getDsRes();
    return  Tools.getFHAddInfo(array,"cpws",4);
}


rule "D308"
when
$ruleResultDTO:RuleResultDTO();
$dynamicRuleInfoDTO:DynamicRuleInfoDTO(doValidationD308(ruleCode,ruleCommonDTO,ruleParamDataDTO,ruleDataSourceMap,$ruleResultDTO));
then
Map<String,Object> extraMap = new HashMap<String,Object>();
extraMap.put("ruleAddInfo",doFhAddInfo($dynamicRuleInfoDTO));
$ruleResultDTO.setResult(Tools.HIT);
$ruleResultDTO.setExtraResultMap(extraMap);
$dynamicRuleInfoDTO.setRuleResultDTO($ruleResultDTO);
end