package com.fosun.fact.t317;


import com.fosun.fdrools.tools.*;
import com.fosun.fdrools.tools.dto.DynamicRuleInfoDTO;
import com.fosun.fdrools.tools.dto.RuleCommonDTO;
import com.fosun.fdrools.tools.dto.RuleParamDataDTO;
import com.fosun.fdrools.tools.dto.RuleDataSourceDTO;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

function Boolean doValidationT317(String ruleCode,RuleCommonDTO commonDTO,RuleParamDataDTO paramDataDTO,Map ruleDataSourceMap,RuleResultDTO resultDTO){
   Logger.info(" 执行  T317");
    if(!Tools.isRuleCodeOK(ruleCode,"T317")){
        return Boolean.FALSE;
    }
    
    if(!ruleDataSourceMap.isEmpty()){
        //借款类型为"1.个人信贷"的笔数 且 状态=审核中” 记录数
        int count = 0;
        //91数据源
        RuleDataSourceDTO afDataSource = (RuleDataSourceDTO)ruleDataSourceMap.get("1003");
        JSONArray resArray = (JSONArray)afDataSource.getDsRes();
        if(resArray != null){
            for(int i = 0; i < resArray.size(); i++ ){
                JSONObject tempJson = resArray.getJSONObject(i);
                //借款类型 ("0","未知"), ("1","个人信贷"), ("2","个人抵押"), ("3","企业信"), ("4","企业抵押")
                //借款状态 ("0","未知"), ("1","拒贷"), ("2","批贷已放款"), ("3","待放款(3同6意义相同)"), ("4","借款人放弃申请"), ("5","审核中"), ("6","待放款(3同6意义相同)")
                String borrowTypeTemp = tempJson.getString("borrowtype");
                String borrowStateTemp = tempJson.getString("borrowstate");
                if("1".equals(borrowTypeTemp) && "5".equals(borrowStateTemp)){
                    count ++ ;
                }
            }
            if(count > 0){
                return Boolean.TRUE;
            }
       }
       
    }
    
    return Boolean.FALSE;
}

rule "T317"
when

$ruleResultDTO:RuleResultDTO();
$dynamicRuleInfoDTO:DynamicRuleInfoDTO(doValidationT317(ruleCode,ruleCommonDTO,ruleParamDataDTO,ruleDataSourceMap,$ruleResultDTO));
then

Map<String,Object> extraMap = new HashMap<String,Object>();
extraMap.put("testMap",123);
$ruleResultDTO.setResult(Tools.HIT);
$ruleResultDTO.setExtraResultMap(extraMap);
$dynamicRuleInfoDTO.setRuleResultDTO($ruleResultDTO);
end