package com.fosun.fact.d310;


import com.fosun.fdrools.tools.*;
import com.fosun.fdrools.tools.dto.DynamicRuleInfoDTO;
import com.fosun.fdrools.tools.dto.RuleCommonDTO;
import com.fosun.fdrools.tools.dto.RuleParamDataDTO;
import com.fosun.fdrools.tools.dto.RuleDataSourceDTO;

import com.alibaba.fastjson.JSONObject;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONArray;

function Boolean doValidationD310(String ruleCode,RuleCommonDTO commonDTO,RuleParamDataDTO paramDataDTO,Map ruleDataSourceMap,RuleResultDTO resultDTO){
   Logger.info(" 执行  D310");
    if(!Tools.isRuleCodeOK(ruleCode,"D310")){
        return Boolean.FALSE;
    }
    
    if(!ruleDataSourceMap.isEmpty()){
       RuleDataSourceDTO fhSxDataSource = (RuleDataSourceDTO)ruleDataSourceMap.get("FHKtgg");
       JSONArray array = (JSONArray)fhSxDataSource.getDsRes();
       JSONObject reqObj = (JSONObject)fhSxDataSource.getDsReq();
       if(array != null && array.size()>0){
           for(int i =0;i<array.size();i++){
               JSONObject object = (JSONObject) array.get(i);
               if("ktgg".equals(object.getString("dataType"))){
                    boolean flag = Tools.result(object.getString("matchratio"),object.getString("sortTimeString"),4); 
                    boolean flagStatus = Tools.checkDefendant(reqObj.getString("personName"),object.getString("defendant"));
                    if(flag&&flagStatus){
                        return Boolean.TRUE;
                    }
               }
           }
       }
    }
    
    return Boolean.FALSE;
}

rule "D310"
when

$ruleResultDTO:RuleResultDTO();
$dynamicRuleInfoDTO:DynamicRuleInfoDTO(doValidationD310(ruleCode,ruleCommonDTO,ruleParamDataDTO,ruleDataSourceMap,$ruleResultDTO));
then

Map<String,Object> extraMap = new HashMap<String,Object>();
extraMap.put("testMap",123);
$ruleResultDTO.setResult(Tools.HIT);
$ruleResultDTO.setExtraResultMap(extraMap);
$dynamicRuleInfoDTO.setRuleResultDTO($ruleResultDTO);
end

