package com.fosun.fact.d131;


import com.fosun.fdrools.tools.*;
import com.fosun.fdrools.tools.dto.DynamicRuleInfoDTO;
import com.fosun.fdrools.tools.dto.RuleCommonDTO;
import com.fosun.fdrools.tools.dto.RuleParamDataDTO;
import com.fosun.fdrools.tools.dto.RuleDataSourceDTO;

import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.JSONArray;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

function Boolean doValidationD131(String ruleCode,RuleCommonDTO commonDTO,RuleParamDataDTO paramDataDTO,Map ruleDataSourceMap,RuleResultDTO resultDTO){
    Logger.info("执行 D131");
    if(!Tools.isRuleCodeOK(ruleCode,"D131")){
        return Boolean.FALSE;
    }
    
     if(!ruleDataSourceMap.isEmpty()){
       RuleDataSourceDTO pyDataSource = (RuleDataSourceDTO)ruleDataSourceMap.get("RZB");
       JSONArray resObj = (JSONArray)pyDataSource.getDsRes();
       JSONObject object = resObj.getJSONObject(0);
       String resultVal = object.getString("result");
       if(!"一致".equals(resultVal)){
           return Boolean.TRUE;
       }
    }
    
    return Boolean.FALSE;
}

rule "D131"
when

$ruleResultDTO:RuleResultDTO();
$dynamicRuleInfoDTO:DynamicRuleInfoDTO(doValidationD131(ruleCode,ruleCommonDTO,ruleParamDataDTO,ruleDataSourceMap,$ruleResultDTO));
then

Map<String,Object> extraMap = new HashMap<String,Object>();
$ruleResultDTO.setResult(Tools.HIT);
$ruleResultDTO.setExtraResultMap(extraMap);
$dynamicRuleInfoDTO.setRuleResultDTO($ruleResultDTO);
end